### PR TITLE
minor travel invoice fixes

### PR DESCRIPTION
**Pull request by shinmm**
Todo:
* #27

### CODE REVIEW

**Comment by shinmm** [comment]
Screen Shot 2021-04-28 at 11 40 03 AM

**Comment by shinmm** [comment]
Will make city names the same format in a bit

**Comment by shinmm** [comment]
Screen Shot 2021-04-28 at 12 03 14 PM

Decided to take out country codes due to sizing and Hong Kong

**Comment by shinmm** [comment]
@pvenkat998 Fixed this is the final
Screen Shot 2021-04-28 at 12 25 50 PM

**Review by pvenkat998 — APPROVED** [review]

**Pull request merged**
